name: ci

on:
  push:
    branches: [ master, 'develop' ]
  pull_request:
    branches: [ master, 'develop' ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run FancyGradient unit tests
      run: xcodebuild clean test -workspace Fancy-Gradient.xcworkspace -scheme "FancyGradient"

